export declare function render(payload: Jason.Actions.RenderPayload): Jason.Actions.Render;
export declare function download(payload: Jason.Actions.RenderPayload): Jason.Actions.Render;
export declare function updateRender(payload: Jason.Actions.UpdateRenderPayload): Jason.Actions.UpdateRender;
export declare function showSave(): Jason.Actions.ShowSave;
export declare function hideSave(): Jason.Actions.HideSave;
export declare function showLoad(): Jason.Actions.ShowLoad;
export declare function hideLoad(): Jason.Actions.HideLoad;
export declare function showRestore(): Jason.Actions.ShowRestore;
export declare function hideRestore(): Jason.Actions.HideRestore;
export declare function showConfirmation(payload: Jason.Actions.ShowConfirmationPayload): Jason.Actions.ShowConfirmation;
export declare function hideConfirmation(payload: Jason.Actions.HideConfirmationPayload): Jason.Actions.HideConfirmation;
export declare function showPreview(payload: Jason.Actions.ShowPreviewPayload): Jason.Actions.ShowPreview;
export declare function hidePreview(payload: Jason.Actions.HidePreviewPayload): Jason.Actions.HidePreview;
export declare function showComplete(payload: Jason.Actions.ShowCompletePayload): Jason.Actions.ShowComplete;
export declare function hideComplete(payload: Jason.Actions.HideCompletePayload): Jason.Actions.HideComplete;
export declare function requestSavedList(payload: Jason.Actions.RequestSavedListPayload): Jason.Actions.RequestSavedList;
export declare function updateSavedList(payload: Jason.Actions.UpdateSavedListPayload): Jason.Actions.UpdateSavedList;
export declare function saveState(payload: Jason.Actions.SaveStatePayload): Jason.Actions.SaveState;
export declare function loadState(payload: Jason.Actions.LoadStatePayload): Jason.Actions.LoadState;
export declare function deleteState(payload: Jason.Actions.DeleteStatePayload): Jason.Actions.DeleteState;
export declare function setWizardPage(payload: Jason.Actions.SetWizardPagePayload): Jason.Actions.SetWizardPage;
